name: Release

# Based on GloriousEggroll's workflow configuration. https://github.com/GloriousEggroll/proton-ge-custom

on:
  release:
    types: [ published ]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      name: ${{ github.ref_name }}

  release:
    name: Release ${{ github.ref_name }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download archive
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.ref_name }}.tar.gz

      - name: Upload to release
        uses: svenstaro/upload-release-action@2.5.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          file: ${{ github.ref_name }}.tar.gz
          overwrite: false

